import { House } from "./types";

export const dummyHouses: House[] = [
  {
    address: { city: "Eindhoven", house: "Mignot en De Blockplein 31 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1182,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 65,
        minMonths: 12,
        nameTag: 21.78,
      },
    },
    status: { name: "available", code: 1 },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 95,
    rooms: 3,
    interestedParties: 0,
    sourceId: "34094460",
    acceptance: "2022-10-01T00:00:00.000Z",
    coordinate: [5.484376, 51.437261],
    image: "/images/56a456-w300-s-fwj/mignot-en-de-blockplein-31",
    id: "36f0a9",
    url: "/woning/eindhoven-mignot-en-de-blockplein-31",
  },
  {
    address: { city: "Waalwijk", house: "Rembrandtpark 68 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 972,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 0,
        minMonths: 12,
        nameTag: null,
      },
    },
    status: { name: "rentinuse", code: 0 },
    attributes: {
      type: {
        category: "house",
        type: "familyhouse",
        subType: "terraced",
        buildType: "existing",
      },
    },
    surface: 104,
    rooms: 5,
    interestedParties: 0,
    sourceId: "34037322",
    acceptance: "2022-10-01T00:00:00.000Z",
    coordinate: [5.078638, 51.677744],
    image: "/images/9fa96f-w300-s-fwj/rembrandtpark-68",
    id: "1c6220",
    url: "/woning/waalwijk-rembrandtpark-68",
  },
  {
    address: { city: "Helmond", house: "Kamerlingh Onnespark 38 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1010,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 40,
        minMonths: 12,
        nameTag: 21.78,
      },
    },
    status: { name: "option", code: 3 },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 83,
    rooms: 3,
    interestedParties: 86,
    sourceId: "34119113",
    acceptance: "2022-10-01T00:00:00.000Z",
    coordinate: [5.637974, 51.476838],
    image: "/images/bf6337-w300-s-fwj/kamerlingh-onnespark-38",
    id: "d4ac1f",
    url: "/woning/helmond-kamerlingh-onnespark-38",
  },
  {
    address: { city: "Rosmalen", house: "Vlondertuinen 31 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1228,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 0,
        minMonths: 12,
        nameTag: null,
      },
    },
    status: { name: "option", code: 3 },
    attributes: {
      type: {
        category: "house",
        type: "familyhouse",
        subType: "middle",
        buildType: "existing",
      },
    },
    surface: 133,
    rooms: 5,
    interestedParties: 57,
    sourceId: "34173999",
    acceptance: "2022-10-01T00:00:00.000Z",
    coordinate: [5.36746, 51.738009],
    image: "/images/779f6c-w300-s-fwj/vlondertuinen-31",
    id: "4a71d8",
    url: "/woning/rosmalen-vlondertuinen-31",
  },
  {
    address: { city: "Eindhoven", house: "Gagelboschplein 519 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1059,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 65,
        minMonths: 12,
        nameTag: 21.78,
      },
    },
    status: { name: "available", code: 1 },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 92,
    rooms: 3,
    interestedParties: 160,
    sourceId: "34098427",
    acceptance: "2022-10-01T00:00:00.000Z",
    coordinate: [5.44667, 51.41858],
    image: "/images/306863-w300-s-fwj/gagelboschplein-519",
    id: "5a0b13",
    url: "/woning/eindhoven-gagelboschplein-519",
  },
  {
    address: { city: "Eindhoven", house: "Gagelboschplein 480 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1045,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 65,
        minMonths: 12,
        nameTag: 21.78,
      },
    },
    status: { name: "available", code: 1 },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 90,
    rooms: 3,
    interestedParties: 126,
    sourceId: "34039675",
    acceptance: "2022-10-01T00:00:00.000Z",
    coordinate: [5.447393, 51.419125],
    image: "/images/4cb1ea-w300-s-fwj/gagelboschplein-480",
    id: "753ca3",
    url: "/woning/eindhoven-gagelboschplein-480",
  },
  {
    address: { city: "Eindhoven", house: "Gagelboschplein 529 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1098,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 65,
        minMonths: 12,
        nameTag: 21.78,
      },
    },
    status: { name: "available", code: 1 },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 100,
    rooms: 3,
    interestedParties: 154,
    sourceId: "34036061",
    acceptance: "2022-10-01T00:00:00.000Z",
    coordinate: [5.446563, 51.418819],
    image: "/images/ae8856-w300-s-fwj/gagelboschplein-529",
    id: "ef5a8a",
    url: "/woning/eindhoven-gagelboschplein-529",
  },
  {
    address: { city: "Eindhoven", house: "Gagelboschplein 474 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1045,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 65,
        minMonths: 12,
        nameTag: 21.78,
      },
    },
    status: { name: "available", code: 1 },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 90,
    rooms: 3,
    interestedParties: 135,
    sourceId: "34036007",
    acceptance: "2022-10-01T00:00:00.000Z",
    coordinate: [5.44744, 51.418534],
    image: "/images/340288-w300-s-fwj/gagelboschplein-474",
    id: "f48f08",
    url: "/woning/eindhoven-gagelboschplein-474",
  },
  {
    address: { city: "Eindhoven", house: "Gagelboschplein 454 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1045,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 65,
        minMonths: 12,
        nameTag: 21.78,
      },
    },
    status: { name: "available", code: 1 },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 90,
    rooms: 3,
    interestedParties: 139,
    sourceId: "34036001",
    acceptance: "2022-10-01T00:00:00.000Z",
    coordinate: [5.447435, 51.418536],
    image: "/images/e1e00c-w300-s-fwj/gagelboschplein-454",
    id: "4b2e89",
    url: "/woning/eindhoven-gagelboschplein-454",
  },
  {
    address: { city: "'s-Hertogenbosch", house: "Willemspoort 148 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1064,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 30,
        minMonths: 12,
        nameTag: 21.78,
      },
    },
    status: { name: "option", code: 3 },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 84,
    rooms: 3,
    interestedParties: 145,
    sourceId: "34111254",
    acceptance: "2022-10-01T00:00:00.000Z",
    coordinate: [5.282371, 51.684626],
    image: "/images/7bd517-w300-s-fwj/willemspoort-148",
    id: "d55e0d",
    url: "/woning/s-hertogenbosch-willemspoort-148",
  },
  {
    address: { city: "Eindhoven", house: "Serlioweg 19 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1135,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 0,
        minMonths: 12,
        nameTag: null,
      },
    },
    status: { name: "available", code: 1 },
    attributes: {
      type: {
        category: "house",
        type: "familyhouse",
        subType: "twounderone",
        buildType: "existing",
      },
    },
    surface: 113,
    rooms: 4,
    interestedParties: 176,
    sourceId: "34094863",
    acceptance: "2022-11-01T00:00:00.000Z",
    coordinate: [5.458263, 51.466599],
    image: "/images/ca9058-w300-s-fwj/serlioweg-19",
    id: "8a8db5",
    url: "/woning/eindhoven-serlioweg-19",
  },
  {
    address: { city: "'s-Hertogenbosch", house: "Kanseliersplein 127 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1153,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 60,
        minMonths: 12,
        nameTag: 21.78,
      },
    },
    status: { name: "rentreserved", code: 2 },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 75,
    rooms: 3,
    interestedParties: 57,
    sourceId: "34651155",
    acceptance: "2022-10-01T00:00:00.000Z",
    coordinate: [5.288048, 51.684703],
    image: "/images/4da44d-w300-s-fwj/kanseliersplein-127",
    id: "23b785",
    url: "/woning/s-hertogenbosch-kanseliersplein-127",
  },
  {
    address: { city: "Eindhoven", house: "De Rungraaf 54 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1060,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 50,
        minMonths: 12,
        nameTag: 21.78,
      },
    },
    status: { name: "option", code: 3 },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 105,
    rooms: 3,
    interestedParties: 231,
    sourceId: "34036567",
    acceptance: "2022-10-01T00:00:00.000Z",
    coordinate: [5.473094, 51.434838],
    image: "/images/3aef46-w300-s-fwj/de-rungraaf-54",
    id: "7fcc40",
    url: "/woning/eindhoven-de-rungraaf-54",
  },
  {
    address: { city: "Veldhoven", house: "Blauwven 46 -C" },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1198,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 0,
        minMonths: 12,
        nameTag: null,
      },
    },
    status: { name: "rentreserved", code: 2 },
    attributes: {
      type: {
        category: "house",
        type: "familyhouse",
        subType: "middle",
        buildType: "existing",
      },
    },
    surface: 122,
    rooms: 5,
    interestedParties: 153,
    sourceId: "34458048",
    acceptance: "2022-09-27T00:00:00.000Z",
    coordinate: [5.389196, 51.437007],
    image: "/images/dee259-w300-s-fwj/blauwven-46-c",
    id: "ace2f5",
    url: "/woning/veldhoven-blauwven-46-c",
  },
  {
    address: { city: "Helmond", house: "Laan door de Veste 74 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 925,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 50,
        minMonths: 25,
        nameTag: 21.78,
      },
    },
    status: { name: "option", code: 3 },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 112,
    rooms: 3,
    interestedParties: 109,
    sourceId: "34189662",
    acceptance: "2022-10-01T00:00:00.000Z",
    coordinate: [5.611079, 51.460142],
    image: "/images/c37ddf-w300-s-fwj/laan-door-de-veste-74",
    id: "cbab97",
    url: "/woning/helmond-laan-door-de-veste-74",
  },
  {
    address: { city: "Rosmalen", house: "Vlondertuinen 11 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1174,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 0,
        minMonths: 12,
        nameTag: null,
      },
    },
    status: { name: "rentreserved", code: 2 },
    attributes: {
      type: {
        category: "house",
        type: "familyhouse",
        subType: "middle",
        buildType: "existing",
      },
    },
    surface: 133,
    rooms: 5,
    interestedParties: 65,
    sourceId: "34038977",
    acceptance: "2022-10-01T00:00:00.000Z",
    coordinate: [5.368573, 51.737608],
    image: "/images/779f6c-w300-s-fwj/vlondertuinen-11",
    id: "b3cb57",
    url: "/woning/rosmalen-vlondertuinen-11",
  },
  {
    address: { city: "Eindhoven", house: "Gelaarsde Kat 131 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1245,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 0,
        minMonths: 12,
        nameTag: null,
      },
    },
    status: { name: "available", code: 1 },
    attributes: {
      type: {
        category: "house",
        type: "familyhouse",
        subType: "terraced",
        buildType: "existing",
      },
    },
    surface: 125,
    rooms: 5,
    interestedParties: 0,
    sourceId: "34070202",
    acceptance: "2022-11-14T00:00:00.000Z",
    coordinate: [5.478334, 51.487183],
    image: "/images/5a1c92-w300-s-fwj/gelaarsde-kat-131",
    id: "774f96",
    url: "/woning/eindhoven-gelaarsde-kat-131",
  },
  {
    address: { city: "Eindhoven", house: "Beryl 3 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1180,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 0,
        minMonths: 25,
        nameTag: null,
      },
    },
    status: { name: "rentreserved", code: 2 },
    attributes: {
      type: {
        category: "house",
        type: "familyhouse",
        subType: "twounderone",
        buildType: "existing",
      },
    },
    surface: 123,
    rooms: 5,
    interestedParties: 152,
    sourceId: "34210787",
    acceptance: "2022-10-01T00:00:00.000Z",
    coordinate: [5.460333, 51.484118],
    image: "/images/fb23b5-w300-s-fwj/beryl-3",
    id: "19be29",
    url: "/woning/eindhoven-beryl-3",
  },
  {
    address: { city: "Eindhoven", house: "Tovermolen 1 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1284,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 0,
        minMonths: 12,
        nameTag: null,
      },
    },
    status: { name: "rentreserved", code: 2 },
    attributes: {
      type: {
        category: "house",
        type: "familyhouse",
        subType: "corner",
        buildType: "existing",
      },
    },
    surface: 126,
    rooms: 5,
    interestedParties: 119,
    sourceId: "34094822",
    acceptance: "2022-11-16T00:00:00.000Z",
    coordinate: [5.478138, 51.488016],
    image: "/images/8938ae-w300-s-fwj/tovermolen-1",
    id: "da06c4",
    url: "/woning/eindhoven-tovermolen-1",
  },
  {
    address: { city: "Weert", house: "Sutjensstraat 30 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 970,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 0,
        minMonths: 12,
        nameTag: null,
      },
    },
    status: { name: "option", code: 3 },
    attributes: {
      type: {
        category: "house",
        type: "familyhouse",
        subType: "middle",
        buildType: "existing",
      },
    },
    surface: 100,
    rooms: 5,
    interestedParties: 25,
    sourceId: "34649764",
    acceptance: "2022-10-01T00:00:00.000Z",
    coordinate: [5.700727, 51.243259],
    image: "/images/96dad3-w300-s-fwj/sutjensstraat-30",
    id: "459c4d",
    url: "/woning/weert-sutjensstraat-30",
  },
  {
    address: { city: "'s-Hertogenbosch", house: "Arena 134 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1062,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 82,
        minMonths: 12,
        nameTag: 21.78,
      },
    },
    status: { name: "option", code: 3 },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 87,
    rooms: 3,
    interestedParties: 73,
    sourceId: "34095555",
    acceptance: "2022-10-01T00:00:00.000Z",
    coordinate: [5.303689, 51.691523],
    image: "/images/11b715-w300-s-fwj/arena-134",
    id: "95a16a",
    url: "/woning/s-hertogenbosch-arena-134",
  },
  {
    address: { city: "Valkenswaard", house: "Koetsierwei 31 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1065,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 0,
        minMonths: 25,
        nameTag: null,
      },
    },
    status: { name: "rentreserved", code: 2 },
    attributes: {
      type: {
        category: "house",
        type: "familyhouse",
        subType: "corner",
        buildType: "existing",
      },
    },
    surface: 110,
    rooms: 5,
    interestedParties: 39,
    sourceId: "34088114",
    acceptance: "2022-10-01T00:00:00.000Z",
    coordinate: [5.430322, 51.363352],
    image: "/images/a83001-w300-s-fwj/koetsierwei-31",
    id: "2b7857",
    url: "/woning/valkenswaard-koetsierwei-31",
  },
  {
    address: { city: "Helmond", house: "Max Euwestraat 2 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1020,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 40,
        minMonths: 12,
        nameTag: 21.78,
      },
    },
    status: { name: "option", code: 3 },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 89,
    rooms: 3,
    interestedParties: 121,
    sourceId: "34119139",
    acceptance: "2022-10-01T00:00:00.000Z",
    coordinate: [5.637625, 51.476542],
    image: "/images/910c28-w300-s-fwj/max-euwestraat-2",
    id: "904290",
    url: "/woning/helmond-max-euwestraat-2",
  },
  {
    address: { city: "Valkenswaard", house: "Koetsierwei 31 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 820,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 211,
        securityDeposit: 0,
        serviceCharges: 0,
        minMonths: 0,
        nameTag: null,
      },
    },
    status: { name: "rentinuse", code: 0, soldOn: "2022-08-26T14:44:36.311Z" },
    attributes: {
      type: {
        category: "house",
        type: "familyhouse",
        subType: "corner",
        buildType: "existing",
      },
    },
    surface: 110,
    rooms: 5,
    interestedParties: 1,
    sourceId: "34038538",
    acceptance: "2022-10-01T00:00:00.000Z",
    coordinate: [5.430322, 51.363352],
    image: "/images/a11e7c-w300-s-fwj/koetsierwei-31",
    id: "25a805",
    url: "/woning/valkenswaard-koetsierwei-31",
  },
  {
    address: { city: "Eindhoven", house: "Lichtstraat 23 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1175,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 70,
        minMonths: 12,
        nameTag: 21.78,
      },
    },
    status: { name: "available", code: 1 },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 99,
    rooms: 3,
    interestedParties: 0,
    sourceId: "34036474",
    acceptance: "2022-11-16T00:00:00.000Z",
    coordinate: [5.472564, 51.438678],
    image: "/images/89aabb-w300-s-fwj/lichtstraat-23",
    id: "4ca052",
    url: "/woning/eindhoven-lichtstraat-23",
  },
  {
    address: { city: "Eindhoven", house: "Gerard Philipslaan 335 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1285,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 80,
        minMonths: 25,
        nameTag: 21.78,
      },
    },
    status: { name: "rentinuse", code: 0, soldOn: "2022-09-05T16:44:34.437Z" },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 96,
    rooms: 3,
    interestedParties: 161,
    sourceId: "34570016",
    acceptance: "2022-10-01T00:00:00.000Z",
    coordinate: [5.463993, 51.443473],
    image: "/images/71bd58-w300-s-fwj/gerard-philipslaan-335",
    id: "ddb109",
    url: "/woning/eindhoven-gerard-philipslaan-335",
  },
  {
    address: { city: "Eindhoven", house: "Fontainebleaulaan 8 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1180,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 0,
        minMonths: 25,
        nameTag: null,
      },
    },
    status: { name: "option", code: 3 },
    attributes: {
      type: {
        category: "house",
        type: "familyhouse",
        subType: "twounderone",
        buildType: "existing",
      },
    },
    surface: 118,
    rooms: 5,
    interestedParties: 212,
    sourceId: "34098168",
    acceptance: "2022-10-01T00:00:00.000Z",
    coordinate: [5.440377, 51.49053],
    image: "/images/c0659d-w300-s-fwj/fontainebleaulaan-8",
    id: "7d2084",
    url: "/woning/eindhoven-fontainebleaulaan-8",
  },
  {
    address: { city: "Helmond", house: "Huiskensstraat 50 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1135,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 0,
        minMonths: 12,
        nameTag: null,
      },
    },
    status: { name: "rentreserved", code: 2 },
    attributes: {
      type: {
        category: "house",
        type: "familyhouse",
        subType: "corner",
        buildType: "existing",
      },
    },
    surface: 142,
    rooms: 4,
    interestedParties: 89,
    sourceId: "34038851",
    acceptance: "2022-10-01T00:00:00.000Z",
    coordinate: [5.608465, 51.460606],
    image: "/images/b43a62-w300-s-fwj/huiskensstraat-50",
    id: "15c746",
    url: "/woning/helmond-huiskensstraat-50",
  },
  {
    address: { city: "Helmond", house: "Prof. Oudlaan 1 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1195,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 0,
        minMonths: 12,
        nameTag: null,
      },
    },
    status: { name: "option", code: 3 },
    attributes: {
      type: {
        category: "house",
        type: "familyhouse",
        subType: "twounderone",
        buildType: "existing",
      },
    },
    surface: 140,
    rooms: 4,
    interestedParties: 130,
    sourceId: "34645801",
    acceptance: "2022-09-01T00:00:00.000Z",
    coordinate: [5.626546, 51.468369],
    image: "/images/320790-w300-s-fwj/prof-oudlaan-1",
    id: "e31d52",
    url: "/woning/helmond-prof-oudlaan-1",
  },
  {
    address: { city: "Eindhoven", house: "Gedempte Gracht 61 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1220,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 1220,
        serviceCharges: 80,
        minMonths: 12,
        nameTag: null,
      },
    },
    status: { name: "option", code: 3 },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 98,
    rooms: 3,
    interestedParties: 185,
    sourceId: "34039066",
    acceptance: "2022-09-01T00:00:00.000Z",
    coordinate: [5.481092, 51.438423],
    image: "/images/a4a4b4-w300-s-fwj/gedempte-gracht-61",
    id: "724fd5",
    url: "/woning/eindhoven-gedempte-gracht-61",
  },
  {
    address: { city: "Eindhoven", house: "Tovermolen 21 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1292,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 0,
        minMonths: 12,
        nameTag: null,
      },
    },
    status: { name: "option", code: 3 },
    attributes: {
      type: {
        category: "house",
        type: "familyhouse",
        subType: "middle",
        buildType: "existing",
      },
    },
    surface: 124,
    rooms: 5,
    interestedParties: 160,
    sourceId: "34110596",
    acceptance: "2022-10-16T00:00:00.000Z",
    coordinate: [5.478673, 51.488452],
    image: "/images/715467-w300-s-fwj/tovermolen-21",
    id: "98db43",
    url: "/woning/eindhoven-tovermolen-21",
  },
  {
    address: { city: "Eindhoven", house: "De Regent 54 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1134,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 1134,
        serviceCharges: 83,
        minMonths: 12,
        nameTag: 21.78,
      },
    },
    status: { name: "rentreserved", code: 2 },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 89,
    rooms: 3,
    interestedParties: 289,
    sourceId: "34035972",
    acceptance: "2022-09-01T00:00:00.000Z",
    coordinate: [5.474255, 51.438418],
    image: "/images/b956f1-w300-s-fwj/de-regent-54",
    id: "a3e283",
    url: "/woning/eindhoven-de-regent-54",
  },
  {
    address: { city: "Nuenen", house: "Hoge Tom 21 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1060,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 1060,
        serviceCharges: 0,
        minMonths: 12,
        nameTag: null,
      },
    },
    status: { name: "available", code: 1 },
    attributes: {
      type: {
        category: "house",
        type: "familyhouse",
        subType: "terraced",
        buildType: "existing",
      },
    },
    surface: 110,
    rooms: 5,
    interestedParties: 195,
    sourceId: "34636252",
    acceptance: "2022-08-01T00:00:00.000Z",
    coordinate: [5.560414, 51.469097],
    image: "/images/340512-w300-s-fwj/hoge-tom-21",
    id: "416642",
    url: "/woning/nuenen-hoge-tom-21",
  },
  {
    address: { city: "Nuenen", house: "Tomakker 91 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1040,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 1040,
        serviceCharges: 0,
        minMonths: 12,
        nameTag: null,
      },
    },
    status: { name: "available", code: 1 },
    attributes: {
      type: {
        category: "house",
        type: "familyhouse",
        subType: "terraced",
        buildType: "existing",
      },
    },
    surface: 110,
    rooms: 5,
    interestedParties: 221,
    sourceId: "34094582",
    acceptance: "2022-08-01T00:00:00.000Z",
    coordinate: [5.560269, 51.469954],
    image: "/images/7ecf21-w300-s-fwj/tomakker-91",
    id: "991ae7",
    url: "/woning/nuenen-tomakker-91",
  },
  {
    address: { city: "Nuenen", house: "Weverstraat 3 b" },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1265,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 0,
        minMonths: 12,
        nameTag: null,
      },
    },
    status: { name: "option", code: 3 },
    attributes: {
      type: {
        category: "house",
        type: "familyhouse",
        subType: "middle",
        buildType: "existing",
      },
    },
    surface: 154,
    rooms: 5,
    interestedParties: 77,
    sourceId: "34095429",
    acceptance: "2022-08-25T00:00:00.000Z",
    coordinate: [5.549947, 51.477337],
    image: "/images/3cfa59-w300-s-fwj/weverstraat-3-b",
    id: "ff14c1",
    url: "/woning/nuenen-weverstraat-3b",
  },
  {
    address: { city: "Eindhoven", house: "Anton Philipslaan 67 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1085,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 85,
        minMonths: 25,
        nameTag: 21.78,
      },
    },
    status: { name: "option", code: 3 },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 88,
    rooms: 3,
    interestedParties: 252,
    sourceId: "34570395",
    acceptance: "2022-09-01T00:00:00.000Z",
    coordinate: [5.465067, 51.442844],
    image: "/images/fcd0db-w300-s-fwj/anton-philipslaan-67",
    id: "68a9b2",
    url: "/woning/eindhoven-anton-philipslaan-67",
  },
  {
    address: { city: "Eindhoven", house: "Anton Philipslaan 69 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1085,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 85,
        minMonths: 25,
        nameTag: 21.78,
      },
    },
    status: { name: "option", code: 3 },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 88,
    rooms: 3,
    interestedParties: 260,
    sourceId: "34570394",
    acceptance: "2022-09-01T00:00:00.000Z",
    coordinate: [5.465003, 51.44279],
    image: "/images/fcd0db-w300-s-fwj/anton-philipslaan-69",
    id: "16d8c3",
    url: "/woning/eindhoven-anton-philipslaan-69",
  },
  {
    address: { city: "Eindhoven", house: "Gagelboschplein 456 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1108,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 75,
        minMonths: 12,
        nameTag: 21.78,
      },
    },
    status: { name: "available", code: 1 },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 90,
    rooms: 3,
    interestedParties: 347,
    sourceId: "34098423",
    acceptance: "2020-02-01T00:00:00.000Z",
    coordinate: [5.447349, 51.41873],
    image: "/images/5ba02f-w300-s-fwj/gagelboschplein-456",
    id: "dc91cd",
    url: "/woning/eindhoven-gagelboschplein-456",
  },
  {
    address: { city: "Eindhoven", house: "Gagelboschplein 419 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1108,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 75,
        minMonths: 12,
        nameTag: 21.78,
      },
    },
    status: { name: "available", code: 1 },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 90,
    rooms: 3,
    interestedParties: 254,
    sourceId: "34098421",
    acceptance: "2022-09-01T00:00:00.000Z",
    coordinate: [5.44792, 51.419071],
    image: "/images/39258d-w300-s-fwj/gagelboschplein-419",
    id: "312dc3",
    url: "/woning/eindhoven-gagelboschplein-419",
  },
  {
    address: { city: "Veldhoven", house: "De Huysacker 71 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1168,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 0,
        minMonths: 12,
        nameTag: null,
      },
    },
    status: { name: "option", code: 3 },
    attributes: {
      type: {
        category: "house",
        type: "familyhouse",
        subType: "middle",
        buildType: "existing",
      },
    },
    surface: 120,
    rooms: 5,
    interestedParties: 177,
    sourceId: "34458056",
    acceptance: "2022-09-26T00:00:00.000Z",
    coordinate: [5.372819, 51.408385],
    image: "/images/6b6806-w300-s-fwj/de-huysacker-71",
    id: "e21da1",
    url: "/woning/veldhoven-de-huysacker-71",
  },
  {
    address: { city: "Nuenen", house: "Tomakker 81 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1040,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 1040,
        serviceCharges: 0,
        minMonths: 12,
        nameTag: null,
      },
    },
    status: { name: "available", code: 1 },
    attributes: {
      type: {
        category: "house",
        type: "familyhouse",
        subType: "terraced",
        buildType: "existing",
      },
    },
    surface: 110,
    rooms: 5,
    interestedParties: 215,
    sourceId: "34082846",
    acceptance: "2022-05-01T00:00:00.000Z",
    coordinate: [5.559871, 51.469813],
    image: "/images/b2d32b-w300-s-fwj/tomakker-81",
    id: "6b08e3",
    url: "/woning/nuenen-tomakker-81",
  },
  {
    address: { city: "'s-Hertogenbosch", house: "Onderwijsboulevard 772 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1170,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 40,
        minMonths: 12,
        nameTag: 21.78,
      },
    },
    status: { name: "available", code: 1 },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 78,
    rooms: 3,
    interestedParties: 150,
    sourceId: "34233114",
    acceptance: "2022-09-01T00:00:00.000Z",
    coordinate: [5.286643, 51.686521],
    image: "/images/74be34-w300-s-fwj/onderwijsboulevard-772",
    id: "8fb9c8",
    url: "/woning/s-hertogenbosch-onderwijsboulevard-772",
  },
  {
    address: { city: "'s-Hertogenbosch", house: "Rijzertlaan 264 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 993,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 45,
        minMonths: 12,
        nameTag: 21.78,
      },
    },
    status: { name: "rentinuse", code: 0 },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 72,
    rooms: 3,
    interestedParties: 177,
    sourceId: "34482240",
    acceptance: "2022-09-01T00:00:00.000Z",
    coordinate: [5.266485, 51.693135],
    image: "/images/1aa8b0-w300-s-fwj/rijzertlaan-264",
    id: "834861",
    url: "/woning/s-hertogenbosch-rijzertlaan-264",
  },
  {
    address: { city: "'s-Hertogenbosch", house: "Willemspoort 362 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1064,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 30,
        minMonths: 12,
        nameTag: 21.78,
      },
    },
    status: { name: "rentinuse", code: 0, soldOn: "2022-08-01T14:44:33.486Z" },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 76,
    rooms: 3,
    interestedParties: 145,
    sourceId: "34259760",
    acceptance: "2022-08-01T00:00:00.000Z",
    coordinate: [5.280995, 51.685428],
    image: "/images/925fb2-w300-s-fwj/willemspoort-362",
    id: "7e81a8",
    url: "/woning/s-hertogenbosch-willemspoort-362",
  },
  {
    address: { city: "Eindhoven", house: "Gerard Philipslaan 215 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1115,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 60,
        minMonths: 25,
        nameTag: 21.78,
      },
    },
    status: { name: "rentinuse", code: 0 },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 82,
    rooms: 3,
    interestedParties: 324,
    sourceId: "34570120",
    acceptance: "2022-09-01T00:00:00.000Z",
    coordinate: [5.463964, 51.443449],
    image: "/images/71bd58-w300-s-fwj/gerard-philipslaan-215",
    id: "50e4da",
    url: "/woning/eindhoven-gerard-philipslaan-215",
  },
  {
    address: { city: "Nuenen", house: "Tomakker 64 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1065,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 1,
        serviceCharges: 0,
        minMonths: 12,
        nameTag: null,
      },
    },
    status: { name: "rentreserved", code: 2 },
    attributes: {
      type: {
        category: "house",
        type: "familyhouse",
        subType: "terraced",
        buildType: "existing",
      },
    },
    surface: 110,
    rooms: 5,
    interestedParties: 167,
    sourceId: "34094570",
    acceptance: "2022-04-01T00:00:00.000Z",
    coordinate: [5.556645, 51.47058],
    image: "/images/9450f2-w300-s-fwj/tomakker-64",
    id: "77b6d6",
    url: "/woning/nuenen-tomakker-64",
  },
  {
    address: { city: "Veldhoven", house: "Bergerhei 18 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1089,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 0,
        minMonths: 12,
        nameTag: null,
      },
    },
    status: { name: "rentinuse", code: 0, soldOn: "2022-09-05T16:45:03.888Z" },
    attributes: {
      type: {
        category: "house",
        type: "familyhouse",
        subType: "terraced",
        buildType: "existing",
      },
    },
    surface: 123,
    rooms: 5,
    interestedParties: 315,
    sourceId: "34036101",
    acceptance: "2022-08-01T00:00:00.000Z",
    coordinate: [5.394402, 51.428075],
    image: "/images/7a9d1a-w300-s-fwj/bergerhei-18",
    id: "dafb08",
    url: "/woning/veldhoven-bergerhei-18",
  },
  {
    address: { city: "Eindhoven", house: "Lichtstraat 81 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1225,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 70,
        minMonths: 12,
        nameTag: null,
      },
    },
    status: { name: "available", code: 1 },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 103,
    rooms: 3,
    interestedParties: 174,
    sourceId: "34039850",
    acceptance: "2022-08-01T00:00:00.000Z",
    coordinate: [5.472304, 51.438744],
    image: "/images/8d4153-w300-s-fwj/lichtstraat-81",
    id: "d164af",
    url: "/woning/eindhoven-lichtstraat-81",
  },
  {
    address: { city: "Eindhoven", house: "Fontainebleaulaan 2 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1180,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 0,
        minMonths: 25,
        nameTag: null,
      },
    },
    status: { name: "option", code: 3 },
    attributes: {
      type: {
        category: "house",
        type: "familyhouse",
        subType: "corner",
        buildType: "existing",
      },
    },
    surface: 118,
    rooms: 5,
    interestedParties: 429,
    sourceId: "34098171",
    acceptance: "2022-09-16T00:00:00.000Z",
    coordinate: [5.440651, 51.490225],
    image: "/images/cddfbe-w300-s-fwj/fontainebleaulaan-2",
    id: "c975aa",
    url: "/woning/eindhoven-fontainebleaulaan-2",
  },
  {
    address: { city: "Heesch", house: "De Sikkel 62 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 980,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 0,
        minMonths: 12,
        nameTag: null,
      },
    },
    status: { name: "rentinuse", code: 0 },
    attributes: {
      type: {
        category: "house",
        type: "familyhouse",
        subType: "corner",
        buildType: "existing",
      },
    },
    surface: 135,
    rooms: 5,
    interestedParties: 81,
    sourceId: "34097266",
    acceptance: "2022-09-01T00:00:00.000Z",
    coordinate: [5.538536, 51.730762],
    image: "/images/412ada-w300-s-fwj/de-sikkel-62",
    id: "a4f9db",
    url: "/woning/heesch-de-sikkel-62",
  },
  {
    address: { city: "Valkenswaard", house: "Koetsierwei 7 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 945,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 0,
        minMonths: 0,
        nameTag: null,
      },
    },
    status: { name: "available", code: 1 },
    attributes: {
      type: {
        category: "house",
        type: "familyhouse",
        subType: "middle",
        buildType: "existing",
      },
    },
    surface: 120,
    rooms: 5,
    interestedParties: 278,
    sourceId: "34037042",
    acceptance: "2022-08-01T00:00:00.000Z",
    coordinate: [5.431454, 51.363322],
    image: "/images/95942e-w300-s-fwj/koetsierwei-7",
    id: "80de8e",
    url: "/woning/valkenswaard-koetsierwei-7",
  },
  {
    address: { city: "Helmond", house: "Laan door de Veste 89 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 925,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 59,
        minMonths: 25,
        nameTag: 21.78,
      },
    },
    status: { name: "available", code: 1 },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 113,
    rooms: 3,
    interestedParties: 288,
    sourceId: "34189621",
    acceptance: "2022-08-01T00:00:00.000Z",
    coordinate: [5.611311, 51.459876],
    image: "/images/6d16c5-w300-s-fwj/laan-door-de-veste-89",
    id: "762437",
    url: "/woning/helmond-laan-door-de-veste-89",
  },
  {
    address: { city: "'s-Hertogenbosch", house: "Meester Spoermekerlaan 44 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 909,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 53,
        minMonths: 12,
        nameTag: null,
      },
    },
    status: { name: "rentinuse", code: 0, soldOn: "2022-08-12T08:44:39.883Z" },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 87,
    rooms: 3,
    interestedParties: 164,
    sourceId: "34099360",
    acceptance: "2022-08-01T00:00:00.000Z",
    coordinate: [5.291013, 51.728347],
    image: "/images/78fcd0-w300-s-fwj/meester-spoermekerlaan-44",
    id: "13a6b2",
    url: "/woning/s-hertogenbosch-meester-spoermekerlaan-44",
  },
  {
    address: { city: "'s-Hertogenbosch", house: "Meester Spoermekerlaan 36 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 909,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 53,
        minMonths: 12,
        nameTag: null,
      },
    },
    status: { name: "rentinuse", code: 0 },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 87,
    rooms: 3,
    interestedParties: 263,
    sourceId: "34036037",
    acceptance: "2022-08-01T00:00:00.000Z",
    coordinate: [5.291044, 51.728362],
    image: "/images/2fd64d-w300-s-fwj/meester-spoermekerlaan-36",
    id: "b39a41",
    url: "/woning/s-hertogenbosch-meester-spoermekerlaan-36",
  },
  {
    address: { city: "Uden", house: "Ploeg 79 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1124,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 0,
        minMonths: 12,
        nameTag: null,
      },
    },
    status: { name: "rentinuse", code: 0, soldOn: "2022-09-05T16:44:47.002Z" },
    attributes: {
      type: {
        category: "house",
        type: "familyhouse",
        subType: "twounderone",
        buildType: "existing",
      },
    },
    surface: 118,
    rooms: 5,
    interestedParties: 64,
    sourceId: "34094729",
    acceptance: "2022-08-01T00:00:00.000Z",
    coordinate: [5.616595, 51.649875],
    image: "/images/28901f-w300-s-fwj/ploeg-79",
    id: "4b73ca",
    url: "/woning/uden-ploeg-79",
  },
  {
    address: { city: "Eindhoven", house: "Gagelboschplein 497 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1034,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 65,
        minMonths: 12,
        nameTag: 21.78,
      },
    },
    status: { name: "available", code: 1 },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 89,
    rooms: 3,
    interestedParties: 407,
    sourceId: "34036012",
    acceptance: "2022-08-01T00:00:00.000Z",
    coordinate: [5.447511, 51.419144],
    image: "/images/d7962b-w300-s-fwj/gagelboschplein-497",
    id: "ac26f3",
    url: "/woning/eindhoven-gagelboschplein-497",
  },
  {
    address: { city: "Eindhoven", house: "Meerwater 102 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1115,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 85,
        minMonths: 12,
        nameTag: null,
      },
    },
    status: { name: "rentinuse", code: 0 },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 108,
    rooms: 3,
    interestedParties: 183,
    sourceId: "34038595",
    acceptance: "2022-08-01T00:00:00.000Z",
    coordinate: [5.407932, 51.442335],
    image: "/images/30cc02-w300-s-fwj/meerwater-102",
    id: "c568cf",
    url: "/woning/eindhoven-meerwater-102",
  },
  {
    address: { city: "'s-Hertogenbosch", house: "Willemspoort 366 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1064,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 30,
        minMonths: 12,
        nameTag: 21.78,
      },
    },
    status: { name: "rentinuse", code: 0 },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 84,
    rooms: 3,
    interestedParties: 161,
    sourceId: "34251854",
    acceptance: "2022-08-01T00:00:00.000Z",
    coordinate: [5.281129, 51.685502],
    image: "/images/925fb2-w300-s-fwj/willemspoort-366",
    id: "d17923",
    url: "/woning/s-hertogenbosch-willemspoort-366",
  },
  {
    address: { city: "Eindhoven", house: "Frits Philipslaan 134 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1030,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 80,
        minMonths: 25,
        nameTag: 21.78,
      },
    },
    status: { name: "rentinuse", code: 0 },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 86,
    rooms: 3,
    interestedParties: 213,
    sourceId: "34570230",
    acceptance: "2022-08-01T00:00:00.000Z",
    coordinate: [5.465779, 51.442478],
    image: "/images/d1ec18-w300-s-fwj/frits-philipslaan-134",
    id: "ddde89",
    url: "/woning/eindhoven-frits-philipslaan-134",
  },
  {
    address: { city: "Uden", house: "Ploeg 61 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1100,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 0,
        minMonths: 12,
        nameTag: null,
      },
    },
    status: { name: "rentinuse", code: 0 },
    attributes: {
      type: {
        category: "house",
        type: "familyhouse",
        subType: "twounderone",
        buildType: "existing",
      },
    },
    surface: 118,
    rooms: 5,
    interestedParties: 86,
    sourceId: "34036120",
    acceptance: "2022-07-01T00:00:00.000Z",
    coordinate: [5.617689, 51.650321],
    image: "/images/9d9add-w300-s-fwj/ploeg-61",
    id: "faf566",
    url: "/woning/uden-ploeg-61",
  },
  {
    address: { city: "Eindhoven", house: "Anton Philipslaan 26 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1020,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 75,
        minMonths: 25,
        nameTag: 21.78,
      },
    },
    status: { name: "rentinuse", code: 0, soldOn: "2022-07-19T08:44:31.322Z" },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 84,
    rooms: 3,
    interestedParties: 314,
    sourceId: "34570323",
    acceptance: "2022-08-01T00:00:00.000Z",
    coordinate: [5.464829, 51.443141],
    image: "/images/7969a8-w300-s-fwj/anton-philipslaan-26",
    id: "2c1ad1",
    url: "/woning/eindhoven-anton-philipslaan-26",
  },
  {
    address: { city: "Helmond", house: "de Plaetse 109 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 860,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 60,
        minMonths: 25,
        nameTag: 21.78,
      },
    },
    status: { name: "rentinuse", code: 0, soldOn: "2022-08-18T08:44:34.517Z" },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 100,
    rooms: 3,
    interestedParties: 267,
    sourceId: "34189678",
    acceptance: "2022-07-01T00:00:00.000Z",
    coordinate: [5.610658, 51.459283],
    image: "/images/f77c2a-w300-s-fwj/de-plaetse-109",
    id: "3bb681",
    url: "/woning/helmond-de-plaetse-109",
  },
  {
    address: { city: "Helmond", house: "Kamerlingh Onnespark 4 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 965,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 40,
        minMonths: 12,
        nameTag: 21.78,
      },
    },
    status: { name: "rentinuse", code: 0, soldOn: "2022-09-05T16:44:42.907Z" },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 83,
    rooms: 3,
    interestedParties: 254,
    sourceId: "34119135",
    acceptance: "2022-08-01T00:00:00.000Z",
    coordinate: [5.637909, 51.477175],
    image: "/images/140cc9-w300-s-fwj/kamerlingh-onnespark-4",
    id: "3036eb",
    url: "/woning/helmond-kamerlingh-onnespark-4",
  },
  {
    address: { city: "Best", house: "Salderes 186 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1012,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 0,
        minMonths: 12,
        nameTag: null,
      },
    },
    status: { name: "available", code: 1 },
    attributes: {
      type: {
        category: "house",
        type: "familyhouse",
        subType: "terraced",
        buildType: "existing",
      },
    },
    surface: 108,
    rooms: 5,
    interestedParties: 349,
    sourceId: "34036250",
    acceptance: "2022-07-01T00:00:00.000Z",
    coordinate: [5.390472, 51.516759],
    image: "/images/df9f14-w300-s-fwj/salderes-186",
    id: "b6a4c6",
    url: "/woning/best-salderes-186",
  },
  {
    address: { city: "Eindhoven", house: "De Rungraaf 100 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 985,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 50,
        minMonths: 12,
        nameTag: null,
      },
    },
    status: { name: "rentinuse", code: 0 },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 84,
    rooms: 3,
    interestedParties: 235,
    sourceId: "34036559",
    acceptance: "2022-07-01T00:00:00.000Z",
    coordinate: [5.47333, 51.43454],
    image: "/images/26e265-w300-s-fwj/de-rungraaf-100",
    id: "af1707",
    url: "/woning/eindhoven-de-rungraaf-100",
  },
  {
    address: { city: "Helmond", house: "Laan door de Veste 75 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1020,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 59,
        minMonths: 25,
        nameTag: null,
      },
    },
    status: { name: "rentinuse", code: 0, soldOn: "2022-07-12T08:44:37.569Z" },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 131,
    rooms: 3,
    interestedParties: 66,
    sourceId: "34189637",
    acceptance: "2022-07-16T00:00:00.000Z",
    coordinate: [5.611165, 51.459891],
    image: "/images/9137c4-w300-s-fwj/laan-door-de-veste-75",
    id: "57ebca",
    url: "/woning/helmond-laan-door-de-veste-75",
  },
  {
    address: { city: "'s-Hertogenbosch", house: "Kanseliersplein 4 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1159,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 60,
        minMonths: 12,
        nameTag: null,
      },
    },
    status: { name: "rentinuse", code: 0, soldOn: "2022-07-25T14:44:29.694Z" },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 74,
    rooms: 3,
    interestedParties: 139,
    sourceId: "34632846",
    acceptance: "2022-07-01T00:00:00.000Z",
    coordinate: [5.289053, 51.684561],
    image: "/images/b7077d-w300-s-fwj/kanseliersplein-4",
    id: "31a1ea",
    url: "/woning/s-hertogenbosch-kanseliersplein-4",
  },
  {
    address: { city: "Eindhoven", house: "Lichtstraat 67 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1251,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 100,
        serviceCharges: 70,
        minMonths: 12,
        nameTag: 21.78,
      },
    },
    status: { name: "rentinuse", code: 0, soldOn: "2022-08-08T14:44:36.044Z" },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 87,
    rooms: 3,
    interestedParties: 155,
    sourceId: "34048928",
    acceptance: "2022-08-12T00:00:00.000Z",
    coordinate: [5.472283, 51.4387],
    image: "/images/ecdbad-w300-s-fwj/lichtstraat-67",
    id: "2528ce",
    url: "/woning/eindhoven-lichtstraat-67",
  },
  {
    address: { city: "Helmond", house: "Esdoornhof 4 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1035,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 0,
        minMonths: 12,
        nameTag: null,
      },
    },
    status: { name: "rentinuse", code: 0 },
    attributes: {
      type: {
        category: "house",
        type: "familyhouse",
        subType: "middle",
        buildType: "existing",
      },
    },
    surface: 111,
    rooms: 4,
    interestedParties: 113,
    sourceId: "34099933",
    acceptance: "2022-07-01T00:00:00.000Z",
    coordinate: [5.650987, 51.488536],
    image: "/images/b9a35f-w300-s-fwj/esdoornhof-4",
    id: "a0d452",
    url: "/woning/helmond-esdoornhof-4",
  },
  {
    address: { city: "Eindhoven", house: "Anton Philipslaan 23 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1025,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 65,
        minMonths: 25,
        nameTag: null,
      },
    },
    status: { name: "rentinuse", code: 0 },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 93,
    rooms: 3,
    interestedParties: 315,
    sourceId: "34070199",
    acceptance: "2022-07-01T00:00:00.000Z",
    coordinate: [5.465131, 51.442886],
    image: "/images/941e4d-w300-s-fwj/anton-philipslaan-23",
    id: "9155ba",
    url: "/woning/eindhoven-anton-philipslaan-23",
  },
  {
    address: { city: "Oisterwijk", house: "Laan van KVL 60 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1270,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 60,
        minMonths: 12,
        nameTag: null,
      },
    },
    status: { name: "rentinuse", code: 0, soldOn: "2022-07-26T14:44:36.324Z" },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 103,
    rooms: 3,
    interestedParties: 36,
    sourceId: "34219987",
    acceptance: "2022-07-01T00:00:00.000Z",
    coordinate: [5.186746, 51.581994],
    image: "/images/2fcbbe-w300-s-fwj/laan-van-kvl-60",
    id: "f41e82",
    url: "/woning/oisterwijk-laan-van-kvl-60",
  },
  {
    address: { city: "Eindhoven", house: "Gerard Philipslaan 175 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1095,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 75,
        minMonths: 25,
        nameTag: 21.78,
      },
    },
    status: { name: "rentinuse", code: 0 },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 82,
    rooms: 3,
    interestedParties: 170,
    sourceId: "34569956",
    acceptance: "2022-06-30T00:00:00.000Z",
    coordinate: [5.463917, 51.443473],
    image: "/images/58ac2b-w300-s-fwj/gerard-philipslaan-175",
    id: "16a737",
    url: "/woning/eindhoven-gerard-philipslaan-175",
  },
  {
    address: { city: "Goirle", house: "Boschring 63 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1056,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 0,
        minMonths: 12,
        nameTag: null,
      },
    },
    status: { name: "rentinuse", code: 0 },
    attributes: {
      type: {
        category: "house",
        type: "familyhouse",
        subType: "middle",
        buildType: "existing",
      },
    },
    surface: 125,
    rooms: 5,
    interestedParties: 84,
    sourceId: "34188693",
    acceptance: "2022-07-01T00:00:00.000Z",
    coordinate: [5.056222, 51.535735],
    image: "/images/143095-w300-s-fwj/boschring-63",
    id: "ed2339",
    url: "/woning/goirle-boschring-63",
  },
  {
    address: { city: "Eindhoven", house: "Frits Philipslaan 208 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1040,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 85,
        minMonths: 12,
        nameTag: 21.78,
      },
    },
    status: { name: "rentinuse", code: 0 },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 79,
    rooms: 3,
    interestedParties: 316,
    sourceId: "34570185",
    acceptance: "2022-07-01T00:00:00.000Z",
    coordinate: [5.46551, 51.442325],
    image: "/images/8691d9-w300-s-fwj/frits-philipslaan-208",
    id: "63139a",
    url: "/woning/eindhoven-frits-philipslaan-208",
  },
  {
    address: { city: "Kaatsheuvel", house: "Hoofdpoort 104 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1025,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 1025,
        serviceCharges: 30,
        minMonths: 12,
        nameTag: null,
      },
    },
    status: { name: "rentinuse", code: 0, soldOn: "2022-07-04T14:44:29.630Z" },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 102,
    rooms: 4,
    interestedParties: 35,
    sourceId: "34621529",
    acceptance: "2022-07-01T00:00:00.000Z",
    coordinate: [5.028885, 51.661808],
    image: "/images/c45c59-w300-s-fwj/hoofdpoort-104",
    id: "bd3f24",
    url: "/woning/kaatsheuvel-hoofdpoort-104",
  },
  {
    address: { city: "Eindhoven", house: "Smaragd 4 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1250,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 1250,
        serviceCharges: 0,
        minMonths: 12,
        nameTag: null,
      },
    },
    status: { name: "rentinuse", code: 0 },
    attributes: {
      type: {
        category: "house",
        type: "familyhouse",
        subType: "twounderone",
        buildType: "existing",
      },
    },
    surface: 149,
    rooms: 5,
    interestedParties: 108,
    sourceId: "34094505",
    acceptance: "2022-05-03T00:00:00.000Z",
    coordinate: [5.465596, 51.48559],
    image: "/images/ec3a1b-w300-s-fwj/smaragd-4",
    id: "5db0aa",
    url: "/woning/eindhoven-smaragd-4",
  },
  {
    address: { city: "Eindhoven", house: "Frits Philipslaan 166 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1080,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 65,
        minMonths: 12,
        nameTag: 21.78,
      },
    },
    status: { name: "rentinuse", code: 0, soldOn: "2022-07-01T14:44:30.890Z" },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 104,
    rooms: 4,
    interestedParties: 371,
    sourceId: "34570212",
    acceptance: "2022-07-01T00:00:00.000Z",
    coordinate: [5.465662, 51.442436],
    image: "/images/d1ec18-w300-s-fwj/frits-philipslaan-166",
    id: "bfbbdc",
    url: "/woning/eindhoven-frits-philipslaan-166",
  },
  {
    address: { city: "Uden", house: "Ploeg 20 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1100,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 0,
        minMonths: 12,
        nameTag: null,
      },
    },
    status: { name: "rentinuse", code: 0, soldOn: "2022-06-20T08:44:17.427Z" },
    attributes: {
      type: {
        category: "house",
        type: "familyhouse",
        subType: "twounderone",
        buildType: "existing",
      },
    },
    surface: 118,
    rooms: 6,
    interestedParties: 39,
    sourceId: "34036112",
    acceptance: "2022-06-01T00:00:00.000Z",
    coordinate: [5.617505, 51.649987],
    image: "/images/28901f-w300-s-fwj/ploeg-20",
    id: "6c183b",
    url: "/woning/uden-ploeg-20",
  },
  {
    address: { city: "Eindhoven", house: "Diamantring 6 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1180,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 0,
        minMonths: 25,
        nameTag: null,
      },
    },
    status: { name: "option", code: 3 },
    attributes: {
      type: {
        category: "house",
        type: "familyhouse",
        subType: "twounderone",
        buildType: "existing",
      },
    },
    surface: 123,
    rooms: 5,
    interestedParties: 252,
    sourceId: "34039427",
    acceptance: "2022-06-01T00:00:00.000Z",
    coordinate: [5.459573, 51.48426],
    image: "/images/1e03f2-w300-s-fwj/diamantring-6",
    id: "5dad68",
    url: "/woning/eindhoven-diamantring-6",
  },
  {
    address: { city: "Eindhoven", house: "Frits Philipslaan 150 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1010,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 85,
        minMonths: 25,
        nameTag: 21.78,
      },
    },
    status: { name: "rentinuse", code: 0, soldOn: "2022-07-21T08:44:31.071Z" },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 75,
    rooms: 3,
    interestedParties: 346,
    sourceId: "34570225",
    acceptance: "2022-06-01T00:00:00.000Z",
    coordinate: [5.46541, 51.44226],
    image: "/images/19a047-w300-s-fwj/frits-philipslaan-150",
    id: "e9d2d7",
    url: "/woning/eindhoven-frits-philipslaan-150",
  },
  {
    address: { city: "Eindhoven", house: "Vrijkensven 30 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1130,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 0,
        minMonths: 12,
        nameTag: null,
      },
    },
    status: { name: "rentreserved", code: 2 },
    attributes: {
      type: {
        category: "house",
        type: "familyhouse",
        subType: "terraced",
        buildType: "existing",
      },
    },
    surface: 121,
    rooms: 5,
    interestedParties: 280,
    sourceId: "34035862",
    acceptance: "2022-05-01T00:00:00.000Z",
    coordinate: [5.511654, 51.419628],
    image: "/images/b56fbe-w300-s-fwj/vrijkensven-30",
    id: "6dec3a",
    url: "/woning/eindhoven-vrijkensven-30",
  },
  {
    address: { city: "Eindhoven", house: "Strijpsestraat 144 -40" },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 806,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 60,
        minMonths: 12,
        nameTag: 21.78,
      },
    },
    status: { name: "rentinuse", code: 0 },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 70,
    rooms: 3,
    interestedParties: 587,
    sourceId: "34040632",
    acceptance: "2022-05-01T00:00:00.000Z",
    coordinate: [5.457567, 51.440852],
    image: "/images/126ebc-w300-s-fwj/strijpsestraat-144-40",
    id: "28f644",
    url: "/woning/eindhoven-strijpsestraat-144-40",
  },
  {
    address: { city: "Eindhoven", house: "Frederiklaan 189 -69" },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1063,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 65,
        minMonths: 12,
        nameTag: 21.78,
      },
    },
    status: { name: "rentinuse", code: 0 },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 81,
    rooms: 3,
    interestedParties: 458,
    sourceId: "34036461",
    acceptance: "2022-05-01T00:00:00.000Z",
    coordinate: [5.457293, 51.441807],
    image: "/images/583605-w300-s-fwj/frederiklaan-189-69",
    id: "670b1b",
    url: "/woning/eindhoven-frederiklaan-189-69",
  },
  {
    address: { city: "Best", house: "Oogstvelden 13 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1110,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 0,
        minMonths: 12,
        nameTag: null,
      },
    },
    status: { name: "option", code: 3 },
    attributes: {
      type: {
        category: "house",
        type: "familyhouse",
        subType: "middle",
        buildType: "existing",
      },
    },
    surface: 118,
    rooms: 5,
    interestedParties: 55,
    sourceId: "34110158",
    acceptance: "2022-10-01T00:00:00.000Z",
    coordinate: [5.367667, 51.503939],
    image: "/images/60aea8-w300-s-fwj/oogstvelden-13",
    id: "3c96c2",
    url: "/woning/best-oogstvelden-13",
  },
  {
    address: { city: "Helmond", house: "Kamerlingh Onnespark 42 " },
    prices: {
      category: "rent",
      isPoundHouse: false,
      purchase: {
        price: 0,
        type: "",
        subType: "",
        vatRate: "",
        serviceCostsPerMonth: 0,
      },
      rental: {
        price: 1010,
        type: "permonth",
        subType: "",
        vatRate: "",
        tenantCosts: 0,
        securityDeposit: 0,
        serviceCharges: 40,
        minMonths: 12,
        nameTag: 21.78,
      },
    },
    status: { name: "option", code: 3 },
    attributes: {
      type: {
        category: "apartment",
        type: "",
        subType: "",
        buildType: "existing",
      },
    },
    surface: 83,
    rooms: 3,
    interestedParties: 58,
    sourceId: "34119124",
    acceptance: "2022-10-11T00:00:00.000Z",
    coordinate: [5.637858, 51.476974],
    image: "/images/3d43db-w300-s-fwj/kamerlingh-onnespark-42",
    id: "2eae44",
    url: "/woning/helmond-kamerlingh-onnespark-42",
  },
];
